### ISSUE TITLE
Decoding with a new trained model

### ISSUE THREAD

**Issue by stackoverflow-temp** [clir/clearnlp#13]
Hello Jinho,

I managed to get a new trained pos tagging model, but I'm having trouble decoding with my model.

I went as far as renaming my model to "general-en-pos.xz", replacing the original model in the "clearnlp-general-en-pos-3.2.jar" with mine and creating a new jar keeping the name "clearnlp-general-en-pos-3.2.jar" the same. It still gives me the error below.

java.io.IOException: Stream closed
at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at java.io.DataInputStream.readFully(DataInputStream.java:195)
at java.io.DataInputStream.readFully(DataInputStream.java:169)
at org.tukaani.xz.SingleXZInputStream.initialize(Unknown Source)
at org.tukaani.xz.SingleXZInputStream.(Unknown Source)
at org.tukaani.xz.XZInputStream.(Unknown Source)
at org.tukaani.xz.XZInputStream.(Unknown Source)
at edu.emory.clir.clearnlp.component.utils.NLPUtils.getObjectInputStream(NLPUtils.java:173)
at edu.emory.clir.clearnlp.component.utils.NLPUtils.getPOSTagger(NLPUtils.java:94)
at edu.emory.clir.clearnlp.bin.NLPDecode.getComponents(NLPDecode.java:207)
at edu.emory.clir.clearnlp.bin.NLPDecode.decode(NLPDecode.java:89)
at edu.emory.clir.clearnlp.bin.NLPDecode.(NLPDecode.java:74)
at edu.emory.clir.clearnlp.bin.NLPDecode.main(NLPDecode.java:236)
log4j:WARN No appenders could be found for logger (edu.emory.clir.clearnlp.util.BinUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.NullPointerException
at edu.emory.clir.clearnlp.component.AbstractStatisticalComponent.load(AbstractStatisticalComponent.java:157)
at edu.emory.clir.clearnlp.component.AbstractStatisticalComponent.initDecode(AbstractStatisticalComponent.java:126)
at edu.emory.clir.clearnlp.component.AbstractStatisticalComponent.(AbstractStatisticalComponent.java:99)
at edu.emory.clir.clearnlp.component.mode.pos.AbstractPOSTagger.(AbstractPOSTagger.java:60)
at edu.emory.clir.clearnlp.component.mode.pos.EnglishPOSTagger.(EnglishPOSTagger.java:49)
at edu.emory.clir.clearnlp.component.utils.NLPUtils.getPOSTagger(NLPUtils.java:87)
at edu.emory.clir.clearnlp.component.utils.NLPUtils.getPOSTagger(NLPUtils.java:94)
at edu.emory.clir.clearnlp.bin.NLPDecode.getComponents(NLPDecode.java:207)
at edu.emory.clir.clearnlp.bin.NLPDecode.decode(NLPDecode.java:89)
at edu.emory.clir.clearnlp.bin.NLPDecode.(NLPDecode.java:74)
at edu.emory.clir.clearnlp.bin.NLPDecode.main(NLPDecode.java:236)
Exception in thread "main" java.lang.NullPointerException
at edu.emory.clir.clearnlp.component.mode.pos.AbstractPOSTagger.createStringFeatureVector(AbstractPOSTagger.java:120)
at edu.emory.clir.clearnlp.component.mode.pos.AbstractPOSTagger.createStringFeatureVector(AbstractPOSTagger.java:33)
at edu.emory.clir.clearnlp.component.AbstractStatisticalComponent.decode(AbstractStatisticalComponent.java:294)
at edu.emory.clir.clearnlp.component.AbstractStatisticalComponent.process(AbstractStatisticalComponent.java:267)
at edu.emory.clir.clearnlp.component.mode.pos.AbstractPOSTagger.process(AbstractPOSTagger.java:105)
at edu.emory.clir.clearnlp.bin.NLPDecode.process(NLPDecode.java:163)
at edu.emory.clir.clearnlp.bin.NLPDecode.process(NLPDecode.java:153)
at edu.emory.clir.clearnlp.bin.NLPDecode.decode(NLPDecode.java:107)
at edu.emory.clir.clearnlp.bin.NLPDecode.(NLPDecode.java:74)
at edu.emory.clir.clearnlp.bin.NLPDecode.main(NLPDecode.java:236)

Would appreciate help with moving forward.

Thank you!

**Comment by jdchoi77** [comment]
Sorry; I've been away for the holidays.  Please let me know if this has not been resolved.  Thank you!

best,

Jinho
